//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSoliciting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoSoliciting.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced mode.
        /// </summary>
        internal static string AdvancedMode {
            get {
                return ResourceManager.GetString("AdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change advanced settings unless you know what you are doing..
        /// </summary>
        internal static string AdvancedWarning1 {
            get {
                return ResourceManager.GetString("AdvancedWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine learning model was trained with certain channels in mind..
        /// </summary>
        internal static string AdvancedWarning2 {
            get {
                return ResourceManager.GetString("AdvancedWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat filters.
        /// </summary>
        internal static string ChatFilters {
            get {
                return ResourceManager.GetString("ChatFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community ads.
        /// </summary>
        internal static string CommunityCategory {
            get {
                return ResourceManager.GetString("CommunityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements for general-purpose communities, generally Discord servers.
        /// </summary>
        internal static string CommunityDescription {
            get {
                return ResourceManager.GetString("CommunityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom chat filters.
        /// </summary>
        internal static string EnableCustomChatFilters {
            get {
                return ResourceManager.GetString("EnableCustomChatFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom Party Finder filters.
        /// </summary>
        internal static string EnableCustomPartyFinderFilters {
            get {
                return ResourceManager.GetString("EnableCustomPartyFinderFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter PFs with item level above maximum.
        /// </summary>
        internal static string FilterIlvlPfs {
            get {
                return ResourceManager.GetString("FilterIlvlPfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filters to private Party Finder listings.
        /// </summary>
        internal static string FilterPrivatePfs {
            get {
                return ResourceManager.GetString("FilterPrivatePfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FiltersTab {
            get {
                return ResourceManager.GetString("FiltersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluff.
        /// </summary>
        internal static string FluffCategory {
            get {
                return ResourceManager.GetString("FluffCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages that don&apos;t fall into other categories and are not for content (Party Finder).
        /// </summary>
        internal static string FluffDescription {
            get {
                return ResourceManager.GetString("FluffDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company ads.
        /// </summary>
        internal static string FreeCompanyCategory {
            get {
                return ResourceManager.GetString("FreeCompanyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements for Free Companies.
        /// </summary>
        internal static string FreeCompanyDescription {
            get {
                return ResourceManager.GetString("FreeCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log filtered messages.
        /// </summary>
        internal static string LogFilteredMessages {
            get {
                return ResourceManager.GetString("LogFilteredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log filtered PFs.
        /// </summary>
        internal static string LogFilteredPfs {
            get {
                return ResourceManager.GetString("LogFilteredPfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading model manifest.
        /// </summary>
        internal static string ModelStatusDownloadingManifest {
            get {
                return ResourceManager.GetString("ModelStatusDownloadingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading model.
        /// </summary>
        internal static string ModelStatusDownloadingModel {
            get {
                return ResourceManager.GetString("ModelStatusDownloadingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialised.
        /// </summary>
        internal static string ModelStatusInitialised {
            get {
                return ResourceManager.GetString("ModelStatusInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising model and classifier.
        /// </summary>
        internal static string ModelStatusInitialising {
            get {
                return ResourceManager.GetString("ModelStatusInitialising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to update model.
        /// </summary>
        internal static string ModelStatusPreparing {
            get {
                return ResourceManager.GetString("ModelStatusPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninitialised.
        /// </summary>
        internal static string ModelStatusUninitialised {
            get {
                return ResourceManager.GetString("ModelStatusUninitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string ModelTab {
            get {
                return ResourceManager.GetString("ModelTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last error: {0}.
        /// </summary>
        internal static string ModelTabError {
            get {
                return ResourceManager.GetString("ModelTabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model status: {0}.
        /// </summary>
        internal static string ModelTabStatus {
            get {
                return ResourceManager.GetString("ModelTabStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string ModelTabVersion {
            get {
                return ResourceManager.GetString("ModelTabVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal messages.
        /// </summary>
        internal static string NormalCategory {
            get {
                return ResourceManager.GetString("NormalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal messages that should not be filtered.
        /// </summary>
        internal static string NormalDescription {
            get {
                return ResourceManager.GetString("NormalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other filters.
        /// </summary>
        internal static string OtherFiltersTab {
            get {
                return ResourceManager.GetString("OtherFiltersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the game&apos;s language setting instead of Dalamud&apos;s.
        /// </summary>
        internal static string OtherGameLanguage {
            get {
                return ResourceManager.GetString("OtherGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherTab {
            get {
                return ResourceManager.GetString("OtherTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Finder filters.
        /// </summary>
        internal static string PartyFinderFilters {
            get {
                return ResourceManager.GetString("PartyFinderFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phishing messages.
        /// </summary>
        internal static string PhishingCategory {
            get {
                return ResourceManager.GetString("PhishingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages trying to trick you into revealing your account details in order to steal your account.
        /// </summary>
        internal static string PhishingDescription {
            get {
                return ResourceManager.GetString("PhishingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions to filter.
        /// </summary>
        internal static string RegularExpressionsToFilter {
            get {
                return ResourceManager.GetString("RegularExpressionsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ReportChatTab {
            get {
                return ResourceManager.GetString("ReportChatTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string ReportColumnChannel {
            get {
                return ResourceManager.GetString("ReportColumnChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ReportColumnDescription {
            get {
                return ResourceManager.GetString("ReportColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string ReportColumnHost {
            get {
                return ResourceManager.GetString("ReportColumnHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ReportColumnMessage {
            get {
                return ResourceManager.GetString("ReportColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string ReportColumnReason {
            get {
                return ResourceManager.GetString("ReportColumnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string ReportColumnSender {
            get {
                return ResourceManager.GetString("ReportColumnSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string ReportColumnTimestamp {
            get {
                return ResourceManager.GetString("ReportColumnTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on one of the entries below to report it to the developer as miscategorised..
        /// </summary>
        internal static string ReportHelp {
            get {
                return ResourceManager.GetString("ReportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reporting.
        /// </summary>
        internal static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ReportModalCancel {
            get {
                return ResourceManager.GetString("ReportModalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ReportModalClassificationOther {
            get {
                return ResourceManager.GetString("ReportModalClassificationOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages that don&apos;t fall under any of the other categories..
        /// </summary>
        internal static string ReportModalClassificationOtherDescription {
            get {
                return ResourceManager.GetString("ReportModalClassificationOtherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string ReportModalCopy {
            get {
                return ResourceManager.GetString("ReportModalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting is disabled because your ML model was not functioning when you saw this message..
        /// </summary>
        internal static string ReportModalDisabledBadModel {
            get {
                return ResourceManager.GetString("ReportModalDisabledBadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot report messages filtered because of a custom filter..
        /// </summary>
        internal static string ReportModalDisabledCustom {
            get {
                return ResourceManager.GetString("ReportModalDisabledCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting is disabled because you weren&apos;t filtering for this kind of message at the time you saw it..
        /// </summary>
        internal static string ReportModalDisabledFilterNotEnabled {
            get {
                return ResourceManager.GetString("ReportModalDisabledFilterNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot report messages filtered because of item level..
        /// </summary>
        internal static string ReportModalDisabledItemLevel {
            get {
                return ResourceManager.GetString("ReportModalDisabledItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting is disabled because you must choose a different classification than the original..
        /// </summary>
        internal static string ReportModalDisabledSameClassification {
            get {
                return ResourceManager.GetString("ReportModalDisabledSameClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to custom filters.
        /// </summary>
        internal static string ReportModalGoToCustomButton {
            get {
                return ResourceManager.GetString("ReportModalGoToCustomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting this message will let the developer know that you think this message was incorrectly classified..
        /// </summary>
        internal static string ReportModalHelp1 {
            get {
                return ResourceManager.GetString("ReportModalHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSoliciting only works for English messages. Do not report non-English messages..
        /// </summary>
        internal static string ReportModalHelp2 {
            get {
                return ResourceManager.GetString("ReportModalHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message&apos;s original classification: {0}.
        /// </summary>
        internal static string ReportModalOriginalClassification {
            get {
                return ResourceManager.GetString("ReportModalOriginalClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ReportModalReport {
            get {
                return ResourceManager.GetString("ReportModalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you think this message should have been classified?.
        /// </summary>
        internal static string ReportModalSuggestedClassification {
            get {
                return ResourceManager.GetString("ReportModalSuggestedClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report to {0}.
        /// </summary>
        internal static string ReportModalTitle {
            get {
                return ResourceManager.GetString("ReportModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Finder.
        /// </summary>
        internal static string ReportPartyFinderTab {
            get {
                return ResourceManager.GetString("ReportPartyFinderTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to send.
        /// </summary>
        internal static string ReportStatusFailure {
            get {
                return ResourceManager.GetString("ReportStatusFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending.
        /// </summary>
        internal static string ReportStatusInProgress {
            get {
                return ResourceManager.GetString("ReportStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last report status: {0}.
        /// </summary>
        internal static string ReportStatusMessage {
            get {
                return ResourceManager.GetString("ReportStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent successfully.
        /// </summary>
        internal static string ReportStatusSuccessful {
            get {
                return ResourceManager.GetString("ReportStatusSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string ReportStatusUnknown {
            get {
                return ResourceManager.GetString("ReportStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to report Party Finder listing hosted by {0}..
        /// </summary>
        internal static string ReportToastFailure {
            get {
                return ResourceManager.GetString("ReportToastFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Finder listing hosted by {0} reported successfully..
        /// </summary>
        internal static string ReportToastSuccess {
            get {
                return ResourceManager.GetString("ReportToastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report to NoSoliciting.
        /// </summary>
        internal static string ReportToNoSoliciting {
            get {
                return ResourceManager.GetString("ReportToNoSoliciting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMT (content).
        /// </summary>
        internal static string RmtContentCategory {
            get {
                return ResourceManager.GetString("RmtContentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-money trade involving content (also known as content sellers).
        /// </summary>
        internal static string RmtContentDescription {
            get {
                return ResourceManager.GetString("RmtContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMT (gil).
        /// </summary>
        internal static string RmtGilCategory {
            get {
                return ResourceManager.GetString("RmtGilCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-money trade involving gil or items (also known as RMT bots).
        /// </summary>
        internal static string RmtGilDescription {
            get {
                return ResourceManager.GetString("RmtGilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roleplaying ads.
        /// </summary>
        internal static string RoleplayingCategory {
            get {
                return ResourceManager.GetString("RoleplayingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements for personal RP, RP communities, venues, or anything else related to roleplaying.
        /// </summary>
        internal static string RoleplayingDescription {
            get {
                return ResourceManager.GetString("RoleplayingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save filters.
        /// </summary>
        internal static string SaveFilters {
            get {
                return ResourceManager.GetString("SaveFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show reporting window.
        /// </summary>
        internal static string ShowReportingWindow {
            get {
                return ResourceManager.GetString("ShowReportingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static recruitment.
        /// </summary>
        internal static string StaticCategory {
            get {
                return ResourceManager.GetString("StaticCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statics looking for members or players looking for a static.
        /// </summary>
        internal static string StaticDescription {
            get {
                return ResourceManager.GetString("StaticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static substitutes.
        /// </summary>
        internal static string StaticSubCategory {
            get {
                return ResourceManager.GetString("StaticSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statics looking for fill-ins of missing members for clears.
        /// </summary>
        internal static string StaticSubDescription {
            get {
                return ResourceManager.GetString("StaticSubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrings to filter.
        /// </summary>
        internal static string SubstringsToFilter {
            get {
                return ResourceManager.GetString("SubstringsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade ads.
        /// </summary>
        internal static string TradeCategory {
            get {
                return ResourceManager.GetString("TradeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages advertising trading items or services for gil, such as omnicrafters looking for work or people selling rare items off the market board.
        /// </summary>
        internal static string TradeDescription {
            get {
                return ResourceManager.GetString("TradeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update model.
        /// </summary>
        internal static string UpdateModel {
            get {
                return ResourceManager.GetString("UpdateModel", resourceCulture);
            }
        }
    }
}
